{{- $fullName := include "passbolt.fullname" . -}}
{{- define "postgres.hostname" -}}
{{- if .Values.postgres.enabled -}}
{{- $fullName := include "passbolt.fullname" . -}}
{{- printf "%s-postgres" $fullName -}}
{{- else -}}
{{- .Values.postgres.hostname -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.passbolt.name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "passbolt.labels" . | indent 4 }}
type: Opaque
data:
#  DATASOURCES_DEFAULT_URL: {{ printf "postgres://%s:%s@%s:5432/%s?schema=passbolt" .Values.postgres.user .Values.postgres.password (include "postgres.hostname" .) .Values.postgres.database | b64enc | quote }}
  DATASOURCES_DEFAULT_HOST: {{ include "postgres.hostname" . | b64enc | quote  }}
  DATASOURCES_DEFAULT_PORT: {{ printf "5432" | b64enc | quote }}
  DATASOURCES_DEFAULT_USERNAME: {{ .Values.postgres.user | b64enc | quote }}
  DATASOURCES_DEFAULT_PASSWORD:	{{ .Values.postgres.password | b64enc | quote }}
  DATASOURCES_DEFAULT_DATABASE: {{ .Values.postgres.database | b64enc | quote }}
  DATASOURCES_DEFAULT_DRIVER: {{ printf "Cake\\Database\\Driver\\Postgres" | b64enc | quote }}
  DATASOURCES_DEFAULT_ENCODING: {{ printf "utf8" | b64enc | quote }}