{{- $fullName := include "passbolt.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "passbolt.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "passbolt.name" . }}-passbolt
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: None
  ports:
    - port: {{ .Values.passbolt.service.port }}
      targetPort: {{ .Values.passbolt.service.name }}
      protocol: TCP
      name: {{ .Values.passbolt.service.name }}
