name: trivy-security-scanning
on: push

permissions:
  security-events: write # To upload SARIF files

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Update to latest version
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4 # Update to latest version
        with:
          version: v3.15.4 # Use the latest Helm version

      - name: Set up Python
        uses: actions/setup-python@v5 # Update to latest version
        with:
          python-version: '3.13'

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master # Use latest version
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          scan-ref: './' # Specify the path to your Helm chart directory
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          github-pat: ${{ secrets.PAT }} # Add GitHub token
          severity: 'HIGH,CRITICAL' # Optional: Focus on high/critical vulnerabilities
      - name: Run Trivy with table output for debugging
        run: |
          trivy config --format table --severity HIGH,CRITICAL ./
        continue-on-error: true # Continue even if Trivy finds issues

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3 # Update to latest version
        with:
          sarif_file: 'trivy-results.sarif'
